### PR TITLE
chore: use giphy `fixed_height.url` for gifs

### PR DESCRIPTION
**Pull request by andreruffert**
All gifs have the same height(200px) now.
- Improves download/display speed

**GiphyAPI**
https://github.com/Giphy/GiphyAPI#sample-response-search

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Isn't 200px a bit small?

**Comment by andreruffert** [comment]
I think it's ok but not ideal tho... 😊

screen shot 2016-02-29 at 12 20 28

**Comment by vadimdemedes** [comment]
I think it's way too small. If only there was something like 300-400px, it would be perfect.

**Comment by andreruffert** [comment]
Yep 300-400px would be nice! Sadly the [GiphyAPI](https://github.com/Giphy/GiphyAPI) does not support such sizes :(

Possible solution to prevent showing too large gifs could be to check sizes e.g.
filter the GiphyAPI response `original.height <= 400` ...

**Comment by vadimdemedes** [comment]
Yeah, good idea ;)

**Comment by andreruffert** [comment]
:point_right:  #21 :sparkles:

**Pull request closed without merging**
